db_url := "postgres://postgres:postgres@localhost:5432/offi?sslmode=disable"

default:
    @just --list

deps:
    GOBIN="$(pwd)/bin" go install github.com/ogen-go/ogen/cmd/ogen@v1.12.0
    GOBIN="$(pwd)/bin" go install github.com/pressly/goose/v3/cmd/goose@v3.24.1

build:
    CGO_ENABLED=0 go build -ldflags="-X 'offi/internal/build_info.Version=dev'" -o bin/offi ./cmd/offi

run:
    CGO_ENABLED=0 go run -ldflags="-X 'offi/internal/build_info.Version=dev'" ./cmd/offi

local command:
    docker compose {{command}}

migrate command:
    ./bin/goose -dir ./migrations postgres "{{db_url}}" {{command}}

generate:
    go generate ./...
