// Code generated by "enumer --type=Format --trimprefix=Format"; DO NOT EDIT.

package logstf

import (
	"fmt"
	"strings"
)

const _FormatName = "Unknown6v69v92v2"

var _FormatIndex = [...]uint8{0, 7, 10, 13, 16}

const _FormatLowerName = "unknown6v69v92v2"

func (i Format) String() string {
	if i >= Format(len(_FormatIndex)-1) {
		return fmt.Sprintf("Format(%d)", i)
	}
	return _FormatName[_FormatIndex[i]:_FormatIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _FormatNoOp() {
	var x [1]struct{}
	_ = x[FormatUnknown-(0)]
	_ = x[Format6v6-(1)]
	_ = x[Format9v9-(2)]
	_ = x[Format2v2-(3)]
}

var _FormatValues = []Format{FormatUnknown, Format6v6, Format9v9, Format2v2}

var _FormatNameToValueMap = map[string]Format{
	_FormatName[0:7]:        FormatUnknown,
	_FormatLowerName[0:7]:   FormatUnknown,
	_FormatName[7:10]:       Format6v6,
	_FormatLowerName[7:10]:  Format6v6,
	_FormatName[10:13]:      Format9v9,
	_FormatLowerName[10:13]: Format9v9,
	_FormatName[13:16]:      Format2v2,
	_FormatLowerName[13:16]: Format2v2,
}

var _FormatNames = []string{
	_FormatName[0:7],
	_FormatName[7:10],
	_FormatName[10:13],
	_FormatName[13:16],
}

// FormatString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func FormatString(s string) (Format, error) {
	if val, ok := _FormatNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _FormatNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Format values", s)
}

// FormatValues returns all values of the enum
func FormatValues() []Format {
	return _FormatValues
}

// FormatStrings returns a slice of all String values of the enum
func FormatStrings() []string {
	strs := make([]string, len(_FormatNames))
	copy(strs, _FormatNames)
	return strs
}

// IsAFormat returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Format) IsAFormat() bool {
	for _, v := range _FormatValues {
		if i == v {
			return true
		}
	}
	return false
}
