name: "Build image"

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Set short git commit SHA
        id: vars
        run: |
          calculatedSha="$(git rev-parse --short ${{ github.sha }})"
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV

      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: "ghcr.io/condensedtea/offi"
          tags: $COMMIT_SHORT_SHA

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          file: ./backend/Dockerfile
          context: ./backend
          push: true
          build-args: |
            VERSION=$COMMIT_SHORT_SHA
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref='${{ steps.meta.outputs.tags }}'
          cache-to: type=inline
